### ISSUE TITLE
Battle.net installation failed on Wayland: BLZBNTBTS0000005C

### ISSUE THREAD

**Issue by glyh** [bottlesdevs/programs#292] opened 2024-01-22 13:38 UTC
![image](https://github.com/bottlesdevs/programs/assets/12870742/87aa6eac-44db-41a2-a33c-b7ec41d3d54e)

To reproduce, just create a new gaming environment and install battle.net

Here's the detailed log
```
21:26:52 (INFO) Bottles Started! 

(bottles:548106): Gtk-WARNING **: 21:26:52.721: AdwViewSwitcher 0x571ba32bd330 (viewswitcher) reported min height -6, but sizes must be >= 0
21:26:59 (INFO) Performing Bottles checks… 
21:26:59 (INFO) Dxvks found:
	- dxvk-2.2
 
21:26:59 (INFO) Vkd3ds found:
	- vkd3d-proton-2.9
 
21:26:59 (INFO) Nvapis found:
	- dxvk-nvapi-v0.6.3
 
21:26:59 (INFO) Latencyflexs found:
	- latencyflex-v0.1.1
 
21:26:59 (INFO) Runners found:
	- soda-7.0-9
	- sys-wine-9.0
 
21:26:59 (INFO) Bottles found:
	- blizzard
 
21:27:00 (INFO) Catalog dependencies loaded 
21:27:00 (INFO) Catalog installers loaded 
21:27:00 (INFO) Catalog components loaded 

(bottles:548106): Gtk-WARNING **: 21:27:04.581: No IM module matching GTK_IM_MODULE=fcitx5 found
21:27:06 (INFO) Setting Key sync=fsync for bottle blizzard… 
21:27:06 (INFO) There is no running wineserver. 
21:27:12 (INFO) Installing dependencies 
21:27:12 (INFO) Updating bottle parameters 
21:27:12 (INFO) Setting Key dxvk=True for bottle blizzard… 
21:27:12 (INFO) Setting Key discrete_gpu=True for bottle blizzard… 
21:27:12 (INFO) Executing installer steps 
21:27:12 (WARNING) File [Battle.net-Setup-enUS.exe] already exists in temp, skipping. 
21:27:12 (INFO) Launching an executable… 
fsync: up and running.
wine: Using setpriority to control niceness in the [-10,10] range
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
00c8:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
01a8:err:ole:com_get_class_object apartment not initialised
01b0:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
info:  Game: Agent.exe
info:  DXVK: v2.2
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x682c39b0
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
01b0:err:vulkan:__wine_create_vk_instance_with_callback Failed to create instance, res=-9
err:   DxvkInstance::createInstance: Failed to create Vulkan 1.1 instance
01d4:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
01a0:err:sync:RtlpWaitForCriticalSection section 02C62B6C "?" w
ait timed out in thread 01a0, blocked by 0140, retrying (60 sec)
01a0:err:sync:RtlpWaitForCriticalSection section 02C62B6C "?" wait timed out in thread 01a0, blocked by 0140, retrying (60 sec)
01a0:err:sync:RtlpWaitForCriticalSection section 02C62B6C "?" wait timed out in thread 01a0, blocked by 0140, retrying (60 sec)
01a0:err:sync:RtlpWaitForCriticalSection section 02C62B6C "?" wait timed out in thread 01a0, blocked by 0140, retrying (60 sec)
01a0:err:sync:RtlpWaitForCriticalSection section 02C62B6C "?" wait timed out in thread 01a0, blocked by 0140, retrying (60 sec)
01e4:err:ole:com_get_class_object apartment not initialised
01ec:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
info:  Game: Agent.exe
info:  DXVK: v2.2
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x682c39b0
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
01ec:err:vulkan:__wine_create_vk_instance_with_callback Failed to create instance, res=-9
err:   DxvkInstance::createInstance: Failed to create Vulkan 1.1 instance
0210:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0220:err:ole:com_get_class_object apartment not initialised
0230:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
info:  Game: Agent.exe
info:  DXVK: v2.2
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x682c39b0
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
0230:err:vulkan:__wine_create_vk_instance_with_callback Failed to create instance, res=-9
err:   DxvkInstance::createInstance: Failed to create Vulkan 1.1 instance
0254:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0260:err:ole:com_get_class_object apartment not initialised
0268:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
info:  Game: Agent.exe
info:  DXVK: v2.2
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x682c39b0
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
0268:err:vulkan:__wine_create_vk_instance_with_callback Failed to create instance, res=-9
err:   DxvkInstance::createInstance: Failed to create Vulkan 1.1 instance
028c:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems

```

**Comment by orowith2os** [comment] 2024-01-23 04:02
Looks like a dupe of https://github.com/bottlesdevs/programs/issues/132

**Closed by orowith2os** 2024-01-23 04:02 UTC

**Comment by glyh** [comment] 2024-01-23 04:04
I post there originally, but the issue description said X11, so I'm not sure about that.

**Comment by orowith2os** [comment] 2024-01-23 04:09
If it happened on X11, and it then happens on Wayland, then it's not specific to either display server. It doesn't need a duplicated issue.
